import smtplib
import datetime
import sys

now = datetime.datetime.now()

smtpObj = smtplib.SMTP('smtp.gmail.com', 587)
smtpObj.ehlo()
smtpObj.starttls()
smtpObj.login('SENDER_EMAIL@gmail.com', 'SENDER_PASSWORD')
smtpObj.sendmail('SENDER_EMAIL@gmail.com',
                 'RECIPIENT_EMAIL@gmail.com',
                 'Subject: EMAIL SUBJECT LINE\n'
                 'TO NAME,\n'
                 '\n'
                 'This is an email generated by Python.\n'
                 '\n'
                 'Sincerely,\n'
                 'FROM NAME\n'
                 '\n'
                 'Prepared on ' + now.strftime("%Y-%m-%d") + ' at ' + now.strftime("%H:%M"))
smtpObj.quit()
